[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-functions-install-node"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
